import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja'>
      <body className={inter.className}>
        <div className='flex justify-center items-center flex-col min-h-screen text-white font-mono bg-gray-800'>
          <main className='flex flex-1 justify-center items-center w-screen flex-col'>
            {children}
          </main>
          <footer className='w-full h-6 flex justify-center items-center text-gray-500 text-sm'>
            @Udemy 20024
          </footer>
        </div>
      </body>
    </html>
  );
}
